"""add boleta xml data table

Revision ID: 4cdb600297c9
Revises: 5617d2809a55
Create Date: 2026-04-30 00:56:24.808964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdb600297c9'
down_revision: Union[str, Sequence[str], None] = '5617d2809a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boleta_xml_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boleta_id', sa.Integer(), nullable=False),
    sa.Column('archivo_id', sa.Integer(), nullable=True),
    sa.Column('rut_emisor', sa.String(length=16), nullable=True),
    sa.Column('rut_receptor', sa.String(length=16), nullable=True),
    sa.Column('numero_boleta', sa.String(length=64), nullable=True),
    sa.Column('fecha_boleta', sa.String(length=32), nullable=True),
    sa.Column('total_honorarios', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('liquido_honorarios', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('impuesto_honorarios', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('porcentaje_impuesto', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('descripcion_linea', sa.Text(), nullable=True),
    sa.Column('observaciones_xml', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['boleta_id'], ['boletas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boleta_xml_data_archivo_id'), 'boleta_xml_data', ['archivo_id'], unique=False)
    op.create_index(op.f('ix_boleta_xml_data_boleta_id'), 'boleta_xml_data', ['boleta_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boleta_xml_data_boleta_id'), table_name='boleta_xml_data')
    op.drop_index(op.f('ix_boleta_xml_data_archivo_id'), table_name='boleta_xml_data')
    op.drop_table('boleta_xml_data')
    # ### end Alembic commands ###
