"""add core domain tables

Revision ID: 5617d2809a55
Revises: d9dcc59b1336
Create Date: 2026-04-30 00:50:59.833734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5617d2809a55'
down_revision: Union[str, Sequence[str], None] = 'd9dcc59b1336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut', sa.String(length=16), nullable=False),
    sa.Column('rut_sin_dv', sa.String(length=16), nullable=True),
    sa.Column('nombre_completo', sa.String(length=256), nullable=False),
    sa.Column('email_personal', sa.String(length=256), nullable=True),
    sa.Column('email_dp', sa.String(length=256), nullable=True),
    sa.Column('telefono', sa.String(length=64), nullable=True),
    sa.Column('direccion', sa.String(length=256), nullable=True),
    sa.Column('sede', sa.String(length=128), nullable=True),
    sa.Column('activo', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docentes_rut'), 'docentes', ['rut'], unique=True)
    op.create_table('instituciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_location', sa.String(length=32), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('rut_razon', sa.String(length=16), nullable=False),
    sa.Column('nombre_razon', sa.String(length=256), nullable=False),
    sa.Column('direccion_razon', sa.String(length=256), nullable=True),
    sa.Column('glosa_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instituciones_codigo_location'), 'instituciones', ['codigo_location'], unique=True)
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes_num', sa.Integer(), nullable=False),
    sa.Column('mes_nombre', sa.String(length=32), nullable=False),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes_num', name='uq_periodos_anio_mes')
    )
    op.create_table('boletas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('institucion_id', sa.Integer(), nullable=True),
    sa.Column('emplid', sa.String(length=32), nullable=True),
    sa.Column('empl_rcd', sa.String(length=16), nullable=True),
    sa.Column('monto_bruto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('glosa', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado_recepcion', sa.String(length=32), nullable=True),
    sa.Column('observaciones_recepcion', sa.Text(), nullable=True),
    sa.Column('estado_pago', sa.String(length=32), nullable=True),
    sa.Column('observaciones_pago', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boletas_docente_id'), 'boletas', ['docente_id'], unique=False)
    op.create_index(op.f('ix_boletas_emplid'), 'boletas', ['emplid'], unique=False)
    op.create_index(op.f('ix_boletas_institucion_id'), 'boletas', ['institucion_id'], unique=False)
    op.create_index(op.f('ix_boletas_periodo_id'), 'boletas', ['periodo_id'], unique=False)
    op.create_table('archivos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boleta_id', sa.Integer(), nullable=True),
    sa.Column('periodo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=16), nullable=False),
    sa.Column('nombre_original', sa.String(length=512), nullable=False),
    sa.Column('ruta_relativa', sa.String(length=1024), nullable=False),
    sa.Column('hash_sha256', sa.String(length=128), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('fecha_origen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boleta_id'], ['boletas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_boleta_id'), 'archivos', ['boleta_id'], unique=False)
    op.create_index(op.f('ix_archivos_periodo_id'), 'archivos', ['periodo_id'], unique=False)
    op.create_table('envios_email',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boleta_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('periodo_id', sa.Integer(), nullable=True),
    sa.Column('periodo_label', sa.String(length=32), nullable=True),
    sa.Column('tipo_envio', sa.String(length=32), nullable=False),
    sa.Column('to_email', sa.String(length=256), nullable=False),
    sa.Column('cc_email', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boleta_id'], ['boletas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envios_email_boleta_id'), 'envios_email', ['boleta_id'], unique=False)
    op.create_index(op.f('ix_envios_email_docente_id'), 'envios_email', ['docente_id'], unique=False)
    op.create_index(op.f('ix_envios_email_periodo_id'), 'envios_email', ['periodo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envios_email_periodo_id'), table_name='envios_email')
    op.drop_index(op.f('ix_envios_email_docente_id'), table_name='envios_email')
    op.drop_index(op.f('ix_envios_email_boleta_id'), table_name='envios_email')
    op.drop_table('envios_email')
    op.drop_index(op.f('ix_archivos_periodo_id'), table_name='archivos')
    op.drop_index(op.f('ix_archivos_boleta_id'), table_name='archivos')
    op.drop_table('archivos')
    op.drop_index(op.f('ix_boletas_periodo_id'), table_name='boletas')
    op.drop_index(op.f('ix_boletas_institucion_id'), table_name='boletas')
    op.drop_index(op.f('ix_boletas_emplid'), table_name='boletas')
    op.drop_index(op.f('ix_boletas_docente_id'), table_name='boletas')
    op.drop_table('boletas')
    op.drop_table('periodos')
    op.drop_index(op.f('ix_instituciones_codigo_location'), table_name='instituciones')
    op.drop_table('instituciones')
    op.drop_index(op.f('ix_docentes_rut'), table_name='docentes')
    op.drop_table('docentes')
    # ### end Alembic commands ###
