"""add envios_email periodo estado tipo index

Revision ID: 8369b14f4217
Revises: 88d2150a6bcc
Create Date: 2026-04-30 01:39:18.842017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8369b14f4217'
down_revision: Union[str, Sequence[str], None] = '88d2150a6bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_envios_email_periodo_estado_tipo', 'envios_email', ['periodo_id', 'estado', 'tipo_envio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_envios_email_periodo_estado_tipo', table_name='envios_email')
    # ### end Alembic commands ###
