"""add boletas periodo estado index

Revision ID: 88d2150a6bcc
Revises: 9a7c1685e5d1
Create Date: 2026-04-30 01:38:42.970409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d2150a6bcc'
down_revision: Union[str, Sequence[str], None] = '9a7c1685e5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_boletas_periodo_estado_recepcion', 'boletas', ['periodo_id', 'estado_recepcion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_boletas_periodo_estado_recepcion', table_name='boletas')
    # ### end Alembic commands ###
