"""add remaining api performance indexes

Revision ID: 8b794a6dd566
Revises: 8369b14f4217
Create Date: 2026-04-30 01:40:08.643774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b794a6dd566'
down_revision: Union[str, Sequence[str], None] = '8369b14f4217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_boletas_periodo_emplid', 'boletas', ['periodo_id', 'emplid'], unique=False)
    op.create_index('ix_boletas_periodo_id_id', 'boletas', ['periodo_id', 'id'], unique=False)
    op.create_index('ix_envios_email_periodo_id_id', 'envios_email', ['periodo_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_envios_email_periodo_id_id', table_name='envios_email')
    op.drop_index('ix_boletas_periodo_id_id', table_name='boletas')
    op.drop_index('ix_boletas_periodo_emplid', table_name='boletas')
    # ### end Alembic commands ###
