"""add unique periodo boleta_key

Revision ID: 9a7c1685e5d1
Revises: f9f4d1d5ee66
Create Date: 2026-04-30 01:16:27.751974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7c1685e5d1'
down_revision: Union[str, Sequence[str], None] = 'f9f4d1d5ee66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_boletas_periodo_boleta_key', 'boletas', ['periodo_id', 'boleta_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_boletas_periodo_boleta_key', 'boletas', type_='unique')
    # ### end Alembic commands ###
