"""add boleta key

Revision ID: f9f4d1d5ee66
Revises: 4cdb600297c9
Create Date: 2026-04-30 01:14:17.794829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f4d1d5ee66'
down_revision: Union[str, Sequence[str], None] = '4cdb600297c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boletas', sa.Column('boleta_key', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_boletas_boleta_key'), 'boletas', ['boleta_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boletas_boleta_key'), table_name='boletas')
    op.drop_column('boletas', 'boleta_key')
    # ### end Alembic commands ###
